name: run-benchmarks
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags: '*'

jobs:
  Run-benchmarks:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel ongoing test runs for previous commits
        uses: styfle/cancel-workflow-action@0.11.0
      - uses: actions/checkout@v3
      - name: setup-benchmarks
        run: bash ./.github/setup.sh
        shell: bash
      - name: run-benchmark-flocking
        run: bash ./.github/run-flocking.sh
        shell: bash
      - name: run-benchmark-wolfsheep
        run: bash ./.github/run-wolfsheep.sh
        shell: bash
      - name: run-benchmark-schelling
        run: bash ./.github/run-schelling.sh
        shell: bash
